In [1]:
import requests
import pandas as pd
import psycopg2

base_url = 'https://www.anapioficeandfire.com/api/'

In [2]:
book_list = []
page = 1

while True:
    book_list_response = requests.get(f'{base_url}books', params={'page': page, 'pageSize': 50}).json()
    book_list.extend(book_list_response)
    if not book_list_response:
        break
    page += 1

book_df = pd.DataFrame(book_list)
book_df

,url,name,isbn,authors,numberOfPages,publisher,country,mediaType,released,characters,povCharacters
0,https://www.anapioficeandfire.com/api/books/1,A Game of Thrones,978-0553103540,[George R. R. Martin],694,Bantam Books,United States,Hardcover,1996-08-01T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
1,https://www.anapioficeandfire.com/api/books/2,A Clash of Kings,978-0553108033,[George R. R. Martin],768,Bantam Books,United States,Hardback,1999-02-02T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/books/3,A Storm of Swords,978-0553106633,[George R. R. Martin],992,Bantam Books,United States,Hardcover,2000-10-31T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/books/4,The Hedge Knight,978-0976401100,[George R. R. Martin],164,Dabel Brothers Publishing,United States,GraphicNovel,2005-03-09T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/books/5,A Feast for Crows,978-0553801507,[George R. R. Martin],784,Bantam Books,United Status,Hardcover,2005-11-08T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
5,https://www.anapioficeandfire.com/api/books/6,The Sworn Sword,978-0785126508,[George R. R. Martin],152,Marvel,United States,Hardcover,2008-06-18T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
6,https://www.anapioficeandfire.com/api/books/7,The Mystery Knight,978-0765360267,[George R. R. Martin],416,Tor Fantasy,United States,Paperback,2011-03-29T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
7,https://www.anapioficeandfire.com/api/books/8,A Dance with Dragons,978-0553801477,[George R. R. Martin],1040,Bantam Books,United States,Hardcover,2011-07-12T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
8,https://www.anapioficeandfire.com/api/books/9,The Princess and the Queen,978-0765332066,[George R. R. Martin],784,Tor Books,United States,Hardcover,2013-12-03T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[]
9,https://www.anapioficeandfire.com/api/books/10,The Rogue Prince,978-0345537263,[George R. R. Martin],832,Bantam Books,United States,Hardcover,2014-06-17T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[]
10,https://www.anapioficeandfire.com/api/books/11,The World of Ice and Fire,978-0553805444,"[Elio Garcia, Linda Antonsson, George R. R. Ma...",336,Bantam Books,United States,Hardcover,2014-10-28T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[]
11,https://www.anapioficeandfire.com/api/books/12,A Knight of the Seven Kingdoms,978-0345533487,[George R. R. Martin],368,Bantam Books,United States,Hardcover,2015-10-06T00:00:00,[],[]

In [3]:
houses_list = []
page = 1
while True:
    houses_responce = requests.get(f'{base_url}houses', params={'page': page, 'pageSize': 50}).json()
    houses_list.extend(houses_responce)
    if not houses_responce:
        break
    page +=1
    
houses_df = pd.DataFrame(houses_list)
print(len(houses_df))
houses_df.head(5)

444

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/1,House Algood,The Westerlands,"A golden wreath, on a blue field with a gold b...",,[],[],,,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[]
1,https://www.anapioficeandfire.com/api/houses/2,House Allyrion of Godsgrace,Dorne,"Gyronny Gules and Sable, a hand couped Or",No Foe May Pass,[],[Godsgrace],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/285,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/3,House Amber,The North,,,[],[],,,,,,,[],[],[]
3,https://www.anapioficeandfire.com/api/houses/4,House Ambrose,The Reach,"Or, semy of ants gules",Never Resting,[],[],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/houses/5,House Appleton of Appleton,The Reach,"Or, an apple tree eradicated proper fructed gu...",,[],[Appleton],,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[]

In [4]:
houses_with_titles_list = []
page = 1
while True:
    houses_with_titles_responce = requests.get(f'{base_url}houses', params={'hasTitles': True, 'page': page, 'pageSize': 50}).json()
    houses_with_titles_list.extend(houses_with_titles_responce)
    if not houses_with_titles_responce:
        break
    page +=1
    
houses_with_titles_df = pd.DataFrame(houses_with_titles_list)
print(len(houses_with_titles_df))
houses_with_titles_df.head()

165

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/7,House Arryn of the Eyrie,The Vale,A sky-blue falcon soaring against a white moon...,As High as Honor,"[King of Mountain and Vale (formerly), Lord of...","[The Eyrie (summer), Gates of the Moon (winter)]",https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/16,Coming of the Andals,https://www.anapioficeandfire.com/api/characte...,,[],[https://www.anapioficeandfire.com/api/houses/6],[https://www.anapioficeandfire.com/api/charact...
1,https://www.anapioficeandfire.com/api/houses/8,House Ashford of Ashford,The Reach,"Tenny, a sun in splendour beneath a chevron in...",Our Sun Shines Bright,[Lord of Ashford],[Ashford],,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/10,House Baelish of Harrenhal,The Riverlands,"A field of silver mockingbirds, on a green fie...",,"[Lord Paramount of the Trident, Lord of Harren...",[Harrenhal],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/16,299 AC,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/houses/13,House Banefort of Banefort,The Westerlands,"A black hooded man, on a grey field, within a ...",,[Lord of Banefort],[Banefort],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/229,,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/houses/14,House Bar Emmon of Sharp Point,The Crownlands,"Fretty argent and white, a swordfish embowed h...",,[Lord of Sharp Point],[Sharp Point],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/15,,,,[],[],[https://www.anapioficeandfire.com/api/charact...

In [5]:
conn = psycopg2.connect(host='hh-pgsql-public.ebi.ac.uk', port = '5432', dbname='pfmegrnargs', 
                        user='reader', password='NWDMCE5xdipIjRrp')

In [6]:
with conn.cursor() as cursor:
    cursor.execute('SELECT * FROM rnc_database limit 10')
    rna_10 = cursor.fetchall()
    column_names = [desc[0] for desc in cursor.description]
df_rna_10 = pd.DataFrame(rna_10, columns = column_names)
df_rna_10.head()

,id,timestamp,userstamp,descr,current_release,full_descr,alive,for_release,display_name,project_id,avg_length,min_length,max_length,num_sequences,num_organisms,description,url,example,reference
0,21,2017-05-02,RNACEN,NONCODE,146,NONCODE,Y,,NONCODE,,1130.0,201.0,244296.0,234669,7,is an integrated knowledge database dedicated ...,http://www.noncode.org/,"[{'upi': 'URS000019B796', 'taxid': 9606}, {'up...",[{'title': 'NONCODE 2016: an informative and v...
1,5,2017-05-17,RNACEN,VEGA,98,VEGA,N,,VEGA,PRJEB4568,NaN,NaN,NaN,0,0,is a repository for high-quality gene models p...,http://vega.sanger.ac.uk/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'The GENCODE v7 catalog of human lo...
2,26,2017-05-01,RNACEN,GENCODE,450,GENCODE,N,,GENCODE,,889.0,32.0,205012.0,47677,2,produces high quality reference gene annotatio...,http://gencodegenes.org/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'GENCODE: the reference human genom...
3,1,2017-05-01,RNACEN,ENA,968,ENA,Y,,ENA,,412.0,10.0,900074.0,12086180,814855,provides a comprehensive record of the world's...,https://www.ebi.ac.uk/ena/browser/,"[{'upi': 'URS00002D0E0C', 'taxid': 10090}, {'u...",[{'title': 'The European Nucleotide Archive in...
4,14,2017-05-01,RNACEN,TAIR,982,TAIR,Y,,TAIR,PRJ_TAIR,384.0,19.0,6227.0,4406,1,is a database of genetic and molecular biology...,http://www.arabidopsis.org/,"[{'upi': 'URS0000591E4F', 'taxid': 3702}, {'up...",[{'title': 'The Arabidopsis Information Resour...

In [7]:
with conn.cursor() as cursor:
    cursor.execute('SELECT display_name, num_sequences, num_organisms, url FROM rnc_database limit 10')
    rna_10 = cursor.fetchall()
    column_names = [desc[0] for desc in cursor.description]
    
df_rna_10 = pd.DataFrame(rna_10, columns = column_names)
df_rna_10.head()

,display_name,num_sequences,num_organisms,url
0,NONCODE,234669,7,http://www.noncode.org/
1,VEGA,0,0,http://vega.sanger.ac.uk/
2,GENCODE,47677,2,http://gencodegenes.org/
3,ENA,12086180,814855,https://www.ebi.ac.uk/ena/browser/
4,TAIR,4406,1,http://www.arabidopsis.org/