In [22]:
import pandas as pd
import bottleneck as bn
import numpy as np
import polars as pl

In [23]:
df_pl = pl.read_csv("train.csv")
df_pl.head(3)

shape: (3, 12)
┌─────────────┬──────────┬────────┬────────────────────────────┬───┬──────────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name                       ┆ … ┆ Ticket           ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---                        ┆   ┆ ---              ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str                        ┆   ┆ str              ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪════════════════════════════╪═══╪══════════════════╪═════════╪═══════╪══════════╡
│ 1           ┆ 0        ┆ 3      ┆ Braund, Mr. Owen Harris    ┆ … ┆ A/5 21171        ┆ 7.25    ┆ null  ┆ S        │
│ 2           ┆ 1        ┆ 1      ┆ Cumings, Mrs. John Bradley ┆ … ┆ PC 17599         ┆ 71.2833 ┆ C85   ┆ C        │
│             ┆          ┆        ┆ (Fl…                       ┆   ┆                  ┆         ┆       ┆          │
│ 3           ┆ 1        ┆ 3      ┆ Heikkinen, Miss. Laina     ┆ … ┆ STON/O2. 3101282 ┆ 7.925   ┆ null  ┆ S        │
└─────────────┴──────────┴────────┴────────────────────────────┴───┴──────────────────┴─────────┴───────┴──────────┘

In [24]:
df_pl.null_count()

shape: (1, 12)
┌─────────────┬──────────┬────────┬──────┬───┬────────┬──────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name ┆ … ┆ Ticket ┆ Fare ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---  ┆   ┆ ---    ┆ ---  ┆ ---   ┆ ---      │
│ u32         ┆ u32      ┆ u32    ┆ u32  ┆   ┆ u32    ┆ u32  ┆ u32   ┆ u32      │
╞═════════════╪══════════╪════════╪══════╪═══╪════════╪══════╪═══════╪══════════╡
│ 0           ┆ 0        ┆ 0      ┆ 0    ┆ … ┆ 0      ┆ 0    ┆ 687   ┆ 2        │
└─────────────┴──────────┴────────┴──────┴───┴────────┴──────┴───────┴──────────┘

In [25]:
df_pl.dtypes

[Int64,
 Int64,
 Int64,
 String,
 String,
 Float64,
 Int64,
 Int64,
 String,
 Float64,
 String,
 String]

In [26]:
df_pl.describe()

shape: (9, 13)
┌────────────┬─────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────┬──────────┐
│ statistic  ┆ PassengerId ┆ Survived ┆ Pclass   ┆ … ┆ Ticket    ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---        ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---   ┆ ---      │
│ str        ┆ f64         ┆ f64      ┆ f64      ┆   ┆ str       ┆ f64       ┆ str   ┆ str      │
╞════════════╪═════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════╪══════════╡
│ count      ┆ 891.0       ┆ 891.0    ┆ 891.0    ┆ … ┆ 891       ┆ 891.0     ┆ 204   ┆ 889      │
│ null_count ┆ 0.0         ┆ 0.0      ┆ 0.0      ┆ … ┆ 0         ┆ 0.0       ┆ 687   ┆ 2        │
│ mean       ┆ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ … ┆ null      ┆ 32.204208 ┆ null  ┆ null     │
│ std        ┆ 257.353842  ┆ 0.486592 ┆ 0.836071 ┆ … ┆ null      ┆ 49.693429 ┆ null  ┆ null     │
│ min        ┆ 1.0         ┆ 0.0      ┆ 1.0      ┆ … ┆ 110152    ┆ 0.0       ┆ A10   ┆ C        │
│ 25%        ┆ 224.0       ┆ 0.0      ┆ 2.0      ┆ … ┆ null      ┆ 7.925     ┆ null  ┆ null     │
│ 50%        ┆ 446.0       ┆ 0.0      ┆ 3.0      ┆ … ┆ null      ┆ 14.4542   ┆ null  ┆ null     │
│ 75%        ┆ 669.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ null      ┆ 31.0      ┆ null  ┆ null     │
│ max        ┆ 891.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ WE/P 5735 ┆ 512.3292  ┆ T     ┆ S        │
└────────────┴─────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────┴──────────┘

In [27]:
df_pl.get_column("Pclass").value_counts().sort("Pclass")

shape: (3, 2)
┌────────┬───────┐
│ Pclass ┆ count │
│ ---    ┆ ---   │
│ i64    ┆ u32   │
╞════════╪═══════╡
│ 1      ┆ 216   │
│ 2      ┆ 184   │
│ 3      ┆ 491   │
└────────┴───────┘

In [28]:
df_pl.group_by("Sex").agg(pl.sum("Survived"))

shape: (2, 2)
┌────────┬──────────┐
│ Sex    ┆ Survived │
│ ---    ┆ ---      │
│ str    ┆ i64      │
╞════════╪══════════╡
│ female ┆ 233      │
│ male   ┆ 109      │
└────────┴──────────┘

In [29]:
df_pl.filter(pl.col("Age") > 44).head()

shape: (5, 12)
┌─────────────┬──────────┬────────┬─────────────────────────────────┬───┬────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name                            ┆ … ┆ Ticket     ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---                             ┆   ┆ ---        ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str                             ┆   ┆ str        ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪═════════════════════════════════╪═══╪════════════╪═════════╪═══════╪══════════╡
│ 7           ┆ 0        ┆ 1      ┆ McCarthy, Mr. Timothy J         ┆ … ┆ 17463      ┆ 51.8625 ┆ E46   ┆ S        │
│ 12          ┆ 1        ┆ 1      ┆ Bonnell, Miss. Elizabeth        ┆ … ┆ 113783     ┆ 26.55   ┆ C103  ┆ S        │
│ 16          ┆ 1        ┆ 2      ┆ Hewlett, Mrs. (Mary D Kingcome… ┆ … ┆ 248706     ┆ 16.0    ┆ null  ┆ S        │
│ 34          ┆ 0        ┆ 2      ┆ Wheadon, Mr. Edward H           ┆ … ┆ C.A. 24579 ┆ 10.5    ┆ null  ┆ S        │
│ 53          ┆ 1        ┆ 1      ┆ Harper, Mrs. Henry Sleeper (My… ┆ … ┆ PC 17572   ┆ 76.7292 ┆ D33   ┆ C        │
└─────────────┴──────────┴────────┴─────────────────────────────────┴───┴────────────┴─────────┴───────┴──────────┘

In [30]:
df = pd.read_csv("train.csv")
print(f'Средний возраст пассажиров: {bn.nanmean(df["Age"]):.2f} \nСтандартное отклонение возраста: {bn.nanstd(df["Age"]):.2f}')

Средний возраст пассажиров: 29.70
Стандартное отклонение возраста: 14.52

In [31]:
df["Fare_new"] = df["Fare"].apply(lambda row: row * 1.3)
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_new
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,9.42500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,92.66829
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,10.30250

In [32]:
df_house = pd.read_csv("Housing.csv")
df_house.head(3)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished

In [33]:
df_house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [34]:
df_house.describe()
# Для столбцов bedrooms, bathrooms, stories и parking оптимальным типом данных является np.int8
# Для столбца price -- np.int32
# Для столбца area -- np.int16

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [35]:
df_house["price"] = df_house["price"].astype(np.int32)
df_house["area"] = df_house["area"].astype(np.int16)
df_house["bedrooms"] = df_house["bedrooms"].astype(np.int8)
df_house["bathrooms"] = df_house["bathrooms"].astype(np.int8)
df_house["stories"] = df_house["stories"].astype(np.int8)
df_house["parking"] = df_house["parking"].astype(np.int8)
df_house.info()
# Уменьшили вес датасета на 20 КБ

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int32
 1   area              545 non-null    int16
 2   bedrooms          545 non-null    int8
 3   bathrooms         545 non-null    int8
 4   stories           545 non-null    int8
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int8
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int16(1), int32(1), int8(4), object(7)
memory usage: 35.3+ KB